### ISSUE TITLE
does not download on debian stretch

### ISSUE THREAD

**Issue by RokkuCode** [simonkberg/atom-check-updates#1]
Hi there,
i am on debian stretch (64-bit) and the download does not start. This is the output I get:

``` acu
  ✨ atom-check-updates v0.0.2 ✨

Retrieving information about your distro...
- Detected as running on a Debian-based distro.

Checking for installed stable version...
Current version:
  - None, or older than 1.7.0

Checking for latest stable release...
Latest version:
  - 1.7.2 (changelog: https://git.io/vwO07)

An update is available!
? Upgrade to v1.7.2? Yes
Downloading:
root@Host:/home/user#
```

NPM Version

```
npm -v
1.4.21
```

If you need further infos, please tell me where I find them.

-Holger

**Comment by simonkberg** [comment]
Thanks for reporting, I'm gonna add some better error reporting and I'll also test myself on a stretch image. Are you on alpha 5?

**Comment by simonkberg** [comment]
I have pushed v0.1.0 which should provide more debug information in case a fatal error occurs. However, I also added node 4.2.0+ (LTS) and npm 2+ as minimum requirements (node 4.2.0 shipped with npm 2.14.7). I can't prioritize supporting legacy node versions, sadly :disappointed:

Give it another shot if you want to update npm (and probably node), and let me know if you still encounter issues after that.

**Comment by RokkuCode** [comment]
Thanks for the update, but for me it does not fix the issue. I am on debian stretch/sid, the alpha 5 is the last debian stretch snapshot with the installer. If you test this with an virtual machine, use debian stretch alpha 5 and update to the newest packages. Further I have updated to the latest npm, the debian version is centuries old - hadn't this in sight.

This is the output with the new version of acu:

```
/usr/bin/atom-check-updates
  ✨ atom-check-updates v0.1.0 ✨

Retrieving information about your distro...
- Detected as running on a Debian-based distro.

Checking for installed stable version...
Current version:
  - None, or older than 1.7.0

Checking for latest stable release...
Latest version:
  - 1.7.2 (changelog: https://git.io/vwO07)

An update is available!
? Upgrade to v1.7.2? Yes
Downloading:
root@Host:/home/user
```

It aborts silently directly after printing "Downloading:" on the shell

**Comment by simon-lifelike** [comment]
Just wanna let you know I've been able to reproduce on debian stretch using node 4. Works fine on node stable (5+), but i'll work on a fix for LTS.

**Comment by simonkberg** [comment]
Fixed in v0.1.1

Thanks for reporting!
